language: php
php:
  - '5.6'
env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"
after_success:
    "curl --ftp-create-dirs -T index.html -u $FTP_USER:$FTP_PASSWORD sftp://sftp.dco.gpaas.net"
