language: php
php:
  - '5.6'
env:
  global:
    - "FTP_USER=user"
    - "FTP_PASSWORD=password"
after_success:
    - "lftp --help"
    - "echo 'put index.hmtl' | sftp $FTP_USER:$FTP_PASSWORD@sftp.dc0.gpaas.net"
